import { TaskCard, WatchedWindow, DetectionRule, UserSettings } from '../../shared/types'

const minsAgo = (n: number) => new Date(Date.now() - n * 60 * 1000).toISOString()

export const mockTaskCards: TaskCard[] = [
  {
    id: 'tc-001',
    windowId: 'w-001',
    title: 'PowerShell — Claude Code',
    appName: 'Windows PowerShell',
    status: 'WAITING_FOR_USER',
    priority: 'HIGH',
    detectedReason: 'Waiting for input detected in terminal',
    suggestedAction: 'Review and provide approval',
    lastSeenAt: minsAgo(2),
    lastStateChangeAt: minsAgo(5),
  },
  {
    id: 'tc-002',
    windowId: 'w-002',
    title: 'Vercel Dashboard — deskkeeper',
    appName: 'Google Chrome',
    status: 'FAILED',
    priority: 'CRITICAL',
    detectedReason: 'Deployment failed detected',
    suggestedAction: 'Review build logs and retry',
    lastSeenAt: minsAgo(10),
    lastStateChangeAt: minsAgo(12),
  },
  {
    id: 'tc-003',
    windowId: 'w-003',
    title: 'Runway — Video Export',
    appName: 'Google Chrome',
    status: 'RUNNING',
    priority: 'LOW',
    detectedReason: 'Export in progress',
    suggestedAction: 'Wait for export to complete',
    lastSeenAt: minsAgo(1),
    lastStateChangeAt: minsAgo(8),
  },
  {
    id: 'tc-004',
    windowId: 'w-004',
    title: 'VS Code — deskkeeper',
    appName: 'Visual Studio Code',
    status: 'ACTIVE',
    priority: 'MEDIUM',
    detectedReason: 'Active development session',
    lastSeenAt: minsAgo(0),
    lastStateChangeAt: minsAgo(30),
  },
  {
    id: 'tc-005',
    windowId: 'w-001',
    title: 'Node.js Server — local:3000',
    appName: 'Windows PowerShell',
    status: 'COMPLETED',
    priority: 'MEDIUM',
    detectedReason: 'Server started successfully',
    suggestedAction: 'Review server output',
    lastSeenAt: minsAgo(15),
    lastStateChangeAt: minsAgo(15),
  },
  {
    id: 'tc-006',
    windowId: 'w-005',
    title: 'Figma — DeskKeeper Wireframes',
    appName: 'Google Chrome',
    status: 'IDLE',
    priority: 'LOW',
    detectedReason: 'No recent activity detected',
    suggestedAction: 'Resume or dismiss',
    lastSeenAt: minsAgo(45),
    lastStateChangeAt: minsAgo(45),
  },
]

export const mockWindows: WatchedWindow[] = [
  {
    id: 'w-001',
    title: 'PowerShell — Claude Code',
    appName: 'Windows PowerShell',
    processName: 'powershell.exe',
    monitorName: 'Monitor 1',
    isWatched: true,
    createdAt: minsAgo(120),
    lastSeenAt: minsAgo(2),
  },
  {
    id: 'w-002',
    title: 'Vercel Dashboard — deskkeeper',
    appName: 'Google Chrome',
    processName: 'chrome.exe',
    monitorName: 'Monitor 1',
    isWatched: true,
    createdAt: minsAgo(90),
    lastSeenAt: minsAgo(10),
  },
  {
    id: 'w-003',
    title: 'Runway — Video Export',
    appName: 'Google Chrome',
    processName: 'chrome.exe',
    monitorName: 'Monitor 2',
    isWatched: true,
    createdAt: minsAgo(60),
    lastSeenAt: minsAgo(1),
  },
  {
    id: 'w-004',
    title: 'VS Code — deskkeeper',
    appName: 'Visual Studio Code',
    processName: 'code.exe',
    monitorName: 'Monitor 1',
    isWatched: true,
    createdAt: minsAgo(180),
    lastSeenAt: minsAgo(0),
  },
  {
    id: 'w-005',
    title: 'Figma — DeskKeeper Wireframes',
    appName: 'Google Chrome',
    processName: 'chrome.exe',
    monitorName: 'Monitor 2',
    isWatched: false,
    createdAt: minsAgo(200),
    lastSeenAt: minsAgo(45),
  },
  {
    id: 'w-006',
    title: 'Slack',
    appName: 'Slack',
    processName: 'slack.exe',
    monitorName: 'Monitor 1',
    isWatched: false,
    createdAt: minsAgo(300),
    lastSeenAt: minsAgo(5),
  },
]

export const mockRules: DetectionRule[] = [
  {
    id: 'rule-001',
    label: 'Terminal Waiting for Input',
    status: 'WAITING_FOR_USER',
    keywords: ['waiting for input', 'press any key', 'y/n', 'continue?', 'confirm', 'press enter'],
    priority: 'HIGH',
    suggestedAction: 'Review and provide input',
  },
  {
    id: 'rule-002',
    label: 'Build or Deployment Failed',
    status: 'FAILED',
    keywords: ['error', 'failed', 'failure', 'exception', 'aborted', 'build failed', 'deployment failed'],
    priority: 'CRITICAL',
    suggestedAction: 'Review errors and fix',
  },
  {
    id: 'rule-003',
    label: 'Task In Progress',
    status: 'RUNNING',
    keywords: ['in progress', 'loading', 'uploading', 'exporting', 'compiling', 'processing', 'rendering'],
    priority: 'LOW',
    suggestedAction: 'Wait for completion',
  },
  {
    id: 'rule-004',
    label: 'Task Completed Successfully',
    status: 'COMPLETED',
    keywords: ['completed', 'success', 'done', 'finished', 'ready', 'deployed successfully'],
    priority: 'MEDIUM',
    suggestedAction: 'Review the result',
  },
  {
    id: 'rule-005',
    label: 'Idle or Standby',
    status: 'IDLE',
    keywords: ['idle', 'waiting', 'standby', 'paused', 'no activity'],
    priority: 'LOW',
    suggestedAction: 'Resume or dismiss',
  },
]

export const mockSettings: UserSettings = {
  notificationsEnabled: true,
  notifyOnWaiting: true,
  notifyOnFailed: true,
  notifyOnCompleted: false,
  notificationCooldownMinutes: 5,
  privateModeEnabled: false,
  monitoringPaused: false,
  useAiClassifier: false,
  captureIntervalSeconds: 10,
  staleThresholdMinutes: 10,
  launchOnLogin: false,
  ocrCaptureEnabled: false,
}
